version: '3.9'
services:
  web:
    build: .
    environment:
      WAIT_HOSTS: db:5432
    env_file: .env
    command: ["scripts/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "3000:8000"
    networks:
      - database-network

networks:
  database-network:
    name: database-network
    external: true
